name: rmsg-private-chat
services:
  api:
    build:
      context: C:\rmsg-private-chat-starter\rmsg-private-chat\server
      dockerfile: Dockerfile
    depends_on:
      ollama:
        condition: service_started
        required: true
      qdrant:
        condition: service_started
        required: true
    environment:
      EMBED_MODEL: nomic-embed-text
      LLM_MODEL: llama3.1:8b-instruct-q4_K_M
      NAMESPACE_DEFAULT: industrial
      NUM_CTX: "4096"
      OLLAMA_BASE_URL: http://ollama:11434
      QDRANT_COLLECTION: rmsg_docs
      QDRANT_URL: http://qdrant:6333
      REQUEST_TIMEOUT_SECONDS: "240"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8088"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: C:\rmsg-private-chat-starter\rmsg-private-chat\server
        target: /app
      - type: bind
        source: C:\rmsg-private-chat-starter\rmsg-private-chat\content
        target: /app/content
  ollama:
    environment:
      OLLAMA_KEEP_ALIVE: "600"
      OLLAMA_NUM_PARALLEL: "1"
      OMP_NUM_THREADS: "6"
    image: ollama/ollama:latest
    mem_limit: "10737418240"
    memswap_limit: "10737418240"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 11434
        published: "11434"
        protocol: tcp
    restart: unless-stopped
  qdrant:
    environment:
      QDRANT__LOG_LEVEL: INFO
      QDRANT__STORAGE__USE_MMAP: "true"
    image: qdrant/qdrant:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 6333
        published: "6333"
        protocol: tcp
    restart: unless-stopped
networks:
  default:
    name: rmsg-private-chat_default
