services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rmsg-private-chat-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: